FROM alex2019/bfjfunds:xtradebacktest

### This one is the base image for installing relevenat building tools
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /home/xtradebacktest

COPY ./ /home/xtradebacktest/

WORKDIR /home/xtradebacktest/bots/
ENTRYPOINT  ["python3"] 

## sudo docker rmi alex2019/bfjfunds-private:xtraderbacktest; 
#  sudo docker build -f DockerFile . -t alex2019/bfjfunds-private:xtraderbacktest;